### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yutakahoulette-zz** [yutakahoulette/yutakahoulette.github.io#1]
- [ ] curate illustrations
- [ ] rescan or rephotograph illustrations as needed
- [x] screenshots of dev projects as needed
- [ ] css for browser window
- [ ] css responsive stuff
- [ ] text for dev projects 
- [x] text for about
- [ ] remove unused css
- [ ] hosting stuff
